cask_args appdir: '/Applications'

#Common Taps for the services I install
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'ack'
brew 'bat'
brew 'brotli'
brew 'coreutils'
brew 'dep'
brew 'diff-so-fancy'
brew 'exa'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'gcc'
brew 'geckodriver'
brew 'git'
brew 'git-flow'
brew 'git-lfs'
brew 'gnu-sed'
brew 'gnupg2'
brew 'gnuplot'
brew 'go'
brew 'htop'
brew 'hugo'
brew 'irssi'
brew 'libyaml'
brew 'lynis'
brew 'mas'
brew 'moreutils'
brew 'ncdu'
brew 'neovim'
brew 'nmap'
brew 'openssh'
brew 'openssl'
brew 'pinentry-mac'
brew 'pyenv'
brew 'rbenv'
brew 'ripgrep'
brew 'screen'
brew 'shellcheck'
brew 'sqlite'
brew 'starship'
brew 'ssh-copy-id'
brew 'task'
brew 'tmux'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
brew "upx"
brew "tor"
brew "zola"
brew "zstd"
brew "zlib"
brew "getantibody/tap/antibody"


#Casks
cask 'alfred'
cask 'docker'
cask 'flux'
cask 'chromedriver'
cask 'eloston-chromium'
cask 'iterm2'
cask 'insomnia'
cask 'kap'
cask 'lulu'
cask 'spotify'
cask 'wireshark'

#Mac Applications
mas "Bear", id: 1091189122
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Magnet", id: 441258766
mas "Monit", id: 1014850245
mas "Numbers", id: 409203825
mas "Owly", id: 882812218
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
mas "Slack", id: 803453959
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
