cask_args appdir: '/Applications'

#Common Taps for the services I install
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/services'
tap 'homebrew/versions'

brew 'ack'
brew 'bat'
brew 'brotli'
brew 'chromedriver'
brew 'coreutils'
brew 'dep'
brew 'diff-so-fancy'
brew 'findutils'
brew 'fzf'
brew 'gcc'
brew 'geckodriver'
brew 'git'
brew 'git-flow'
brew 'git-lfs'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnupg2'
brew 'go'
brew 'gpg-agent'
brew 'htop'
brew 'hugo'
brew 'irssi'
brew 'libyaml'
brew 'lynis'
brew 'mas'
brew 'moreutils'
brew 'mysql'
brew 'ncdu'
brew 'neovim'
brew 'nvm'
brew 'openssh'
brew 'openssl'
brew 'pinentry-mac'
brew 'pyenv'
brew 'rbenv'
brew 'screen'
brew 'shellcheck'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'swagger-codegen'
brew 'task'
brew 'tmux'
brew 'wget', args: ['with-iri']
brew 'zsh'
brew 'zsh-completions'
brew "upx"
brew "tor"
brew "zstd"
brew "ethereum/ethereum/ethereum"

#Casks
cask 'alfred'
cask 'docker'
cask 'flux'
cask 'google-chrome'
cask 'google-drive'
cask 'iterm2'
cask 'java'
cask 'kap'
cask 'oni'
cask 'reactotron'
cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'ubersicht'

#Mac Applications
mas "Bear", id: 1091189122
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Magnet", id: 441258766
mas "Monit", id: 1014850245
mas "Numbers", id: 409203825
mas "Owly", id: 882812218
mas "Pages", id: 409201541
mas 'trello'
mas "Xcode", id: 497799835
