[manager]
name = "brew"
config = "~/dotfiles/config/brew/Brewfile"

[shell]
name = "zsh"

[packages]
[packages.rust]
install = [
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh",
    'rustup component add rls rust-analysis rust-src clippy rustfmt',
]
update = ['rustup update']

# [links]
#   [links.zsh]
#     from = "zsh/zshrc"
#     to = "~/.zshrc"
#
# # @todo
#   [links.git]
#     from = ["gitconfig.local", "gitconfig", "gitignore", "gitmessage"]
#     to = ["~/.gitconfig", "~/.gitconfig". "~/.gitignore", "~/.gitmessage"]
#
