[tools]
# specify single or multiple versions
terraform = '1.9.7'
# erlang = ['23.3', '24.0']

# supports everything you can do with .tool-versions currently
# node = ['16', 'prefix:20', 'ref:master', 'path:~/.nodes/14']
