[tools]
# specify single or multiple versions
terraform = "latest"
ruby = "latest"
lua = "latest"
node = "latest"
python = "latest"

# =============================================================================================
# Rust
# =============================================================================================
"cargo:cargo-run-bin" = "latest"
cargo-binstall = "latest"

# =============================================================================================
# Node
# =============================================================================================
"npm:neovim" = "latest"
uv = "latest"
yarn = "latest"

# =============================================================================================
# Python
# =============================================================================================


[settings]
not_found_auto_install = true
cargo_binstall = true
pipx_uvx = true
experimental = true

[settings.python]
default_packages_file = "~/dotfiles/config/default_python_packages"
